apiVersion: v1
kind: ConfigMap
metadata:
  namespace: todo
  name: api-tester-properties
  labels:
    part-of: k8s-todo
    component: backend-server
    name: api-tester
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
data:
  spring_profiles_active: "dev"
  application_role: "ALL"
  postgresql_filepath: "/usr/src/myapp/datasource/postgresql-info.yaml"