apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo
  name: todo-api-test
  labels:
    part-of: k8s-todo
    component: backend-server
    name: todo-api
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-todo
      component: backend-server
      name: api-tester
      instance: todo-api-test
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: k8s-todo
        component: backend-server
        name: api-tester
        instance: todo-api-test
        version: 1.0.0
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: todo-api-test
          image: otteu/todo-api-test:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: http
#          envFrom:
#            - configMapRef:
#                name: todo-api-test-properties
#          startupProbe:
#            httpGet:
#              path: "/startup"
#              port: 8080
#            periodSeconds: 5
#            failureThreshold: 24
#          readinessProbe:
#            httpGet:
#              path: "/readiness"
#              port: 8080
#            periodSeconds: 10
#            failureThreshold: 3
#          livenessProbe:
#            httpGet:
#              path: "/liveness"
#              port: 8080
#            periodSeconds: 10
#            failureThreshold: 3
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
#            - name: files
#              mountPath: /usr/src/myapp/files/dev
            - name: secret-datasource
              mountPath: /usr/src/myapp/datasource
      volumes:
#        - name: files
#          persistentVolumeClaim:
#            claimName: todo-api-test-files
        - name: secret-datasource
          secret:
            secretName: api-tester-mysql