apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: todo
  name: api-tester-default
  labels:
    part-of: k8s-todo
    component: backend-server
    name: todo-api
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-api-test
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120