apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-tester-files
  labels:
    part-of: k8s-todo
    component: backend-server
    name: api-tester
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: "/root/k8s-local-volume/todo"
  # 어느 노드의 파드 생설 할 것인가.
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: kubernetes.io/hostname, operator: In, values: [k8s-master]}