apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo
  name: api-tester-files
  labels:
    part-of: k8s-todo
    component: backend-server
    name: api-tester
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
spec:
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      part-of: k8s-todo
      component: backend-server
      name: api-tester
      instance: api-tester-files