apiVersion: v1
kind: Secret
metadata:
  namespace: todo
  name: api-tester-postgresql
  labels:
    part-of: k8s-todo
    component: backend-server
    name: todo-api
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
stringData:
  postgresql-info.yaml: |            
    url: "jdbc:postgresql://192.168.0.48:5432/todo"
    username: todouser
    password: todouser
    driver-class-name: "org.postgresql.Driver"  
