apiVersion: v1
kind: Secret
metadata:
  namespace: todo
  name: api-tester-mysql
  labels:
    part-of: k8s-todo
    component: backend-server
    name: todo-api
    instance: todo-api-test
    version: 1.0.0
    managed-by: kubectl
stringData:
  mysql-info.yaml: |        
    url: jdbc:mysql://192.168.0.48:3306/todo
    username: todouser
    password: todouser
    driver-class-name: com.mysql.cj.jdbc.Driver  
